language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script: "mvn clean install"

branches:
  only:
    - develop
    
after_success:
  - mvn cobertura:cobertura jacoco:report coveralls:report
